---
kind: Service
apiVersion: v1
metadata:
  name: hello-k8s-service
  namespace: aaron-test
spec:
  type: NodePort
  selector:
    app: hello-k8s
  ports:
    - port: 8080
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-k8s
  namespace: aaron-test
  labels:
    app: hello-k8s
spec:
  replicas: 2
  progressDeadlineSeconds: 600
  minReadySeconds: 20
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
        - name: minikube-get-started
          image: aaronfae/minikube-get-started:1.2.1
          imagePullPolicy: Always
          env:
            - name: TIME_ZONE
              value: GMT+08
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          volumeMounts:
            - name: vol-hello-k8s-config-map
              mountPath: /config/application.yml
              subPath: application.yml
      volumes:
        - name: vol-hello-k8s-config-map
          configMap:
            name: hello-k8s-config-map
            items:
              - key: application.yml
                path: application.yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-k8s-config-map
  namespace: aaron-test
data:
  application.yml: |
    name: aaron
